export default [
  {
    preview: './videos/1.mp4',
    isMv: true,
    title: '每天花一小时化出来的帅脸1235argasg',
    tag: 'Ta1324g 1',
    userHead: './images/2.webp',
    username: 'User 1',
    likeCount: 100,
    isLike: true,
  },
  {
    preview: './videos/2.mp4',
    isMv: true,
    title: 'Basic clothes stuff34345sdhsh',
    tag: 'Tag 52',
    userHead: './images/5.webp',
    username: 'User 2',
    likeCount: 200,
    isLike: false,
  },
  {
    preview: './videos/3.mp4',
    isMv: true,
    title: '官个宣❤24536sdghrwty',
    tag: 'Taazdg 5',
    userHead: './images/6.jpeg',
    username: 'User 5',
    likeCount: 500,
    isLike: true,
  },
  {
    preview: './videos/4.mp4',
    isMv: true,
    title: 'Image 3twrjwrtj',
    tag: 'Tagbb 3',
    userHead: './images/9.jpeg',
    username: 'User 3',
    likeCount: 300,
    isLike: true,
  },
  {
    preview: './videos/5.mp4',
    isMv: true,
    title: 'I相信自己会越来越好的wrtw',
    tag: 'Tag ser4',
    userHead: './images/4.jpeg',
    username: 'User 4',
    likeCount: 400,
    isLike: false,
  },
  {
    preview: './videos/6.mp4',
    isMv: true,
    title: '我的猫喜欢wrty我的宝宝',
    tag: 'T245ag 5',
    userHead: './images/6.jpeg',
    username: 'User 5',
    likeCount: 500,
    isLike: true,
  },
  {
    preview: './videos/7.mp4',
    isMv: true,
    title: 'rwyjkwrty表面上参加：',
    tag: 'Tagu6 2',
    userHead: './images/5.webp',
    username: 'User 2',
    likeCount: 200,
    isLike: false,
  },
  {
    preview: './videos/8.mp4',
    isMv: true,
    title: '爱打nwtryw45扮外号叫什么',
    tag: 'Tag mr5',
    userHead: './images/6.jpeg',
    username: 'User 5',
    likeCount: 500,
    isLike: true,
  },
  {
    preview: './videos/9.mp4',
    isMv: true,
    title: '爱自己nytjarhg会发光',
    tag: 'Tagz 2',
    userHead: './images/5.webp',
    username: 'User 2',
    likeCount: 200,
    isLike: false,
  },
  {
    preview: './videos/10.mp4',
    isMv: true,
    title: '已更mryultprti新',
    tag: 'Tag568 5',
    userHead: './images/6.jpeg',
    username: 'User 5',
    likeCount: 500,
    isLike: true,
  },
  {
    preview: './videos/11.mp4',
    isMv: true,
    title: '用牛逼的nsbfgjiuyoqafb口音说多邻国的第一单元',
    tag: 'Tag356h 2',
    userHead: './images/5.webp',
    username: 'User 2',
    likeCount: 200,
    isLike: false,
  },
  {
    preview: './videos/12.mp4',
    isMv: true,
    title: '夏日的sfgdneytrklzdva风',
    tag: 'Tadgjkg 3',
    userHead: './images/6.jpeg',
    username: 'User 6',
    likeCount: 350,
    isLike: true,
  },
  {
    preview: './images/1.jpeg',
    title: '冬日的asdgtri雪',
    tag: 'Tag56n4',
    userHead: './images/6.jpeg',
    username: 'User 7',
    likeCount: 450,
    isLike: false,
  },
  {
    preview: './images/2.webp',
    title: '春日的jmykj花',
    tag: 'Tagsrm',
    userHead: './images/6.jpeg',
    username: 'User 8',
    likeCount: 150,
    isLike: true,
  },
  {
    preview: './images/3.jpeg',
    title: '秋日的dfgjrt叶',
    tag: 'Tagdrn5',
    userHead: './images/6.jpeg',
    username: 'User 9',
    likeCount: 250,
    isLike: false,
  },
  {
    preview: './images/4.jpeg',
    title: '夜空mxtdf的星',
    tag: 'Tagdsf 2',
    userHead: './images/6.jpeg',
    username: 'User 10',
    likeCount: 350,
    isLike: true,
  },
  {
    preview: './images/5.webp',
    title: '晨曦yuet的光',
    tag: 'Tag124 3',
    userHead: './images/6.jpeg',
    username: 'User 11',
    likeCount: 450,
    isLike: false,
  },
  {
    preview: './images/6.jpeg',
    title: '黄昏dfr4影',
    tag: 'Tag 54',
    userHead: './images/6.jpeg',
    username: 'User 12',
    likeCount: 550,
    isLike: true,
  },
  {
    preview: './images/7.jpeg',
    title: '月光ndft的柔',
    tag: 'Tag 11234',
    userHead: './images/6.jpeg',
    username: 'User 13',
    likeCount: 650,
    isLike: false,
  },
  {
    preview: './images/8.jpeg',
    title: '阳光sd45的暖',
    tag: 'Tag 5dfn',
    userHead: './images/6.jpeg',
    username: 'User 14',
    likeCount: 750,
    isLike: true,
  },
  {
    preview: './images/9.jpeg',
    title: '海风的jdf bsd咸',
    tag: 'Tag 2jk6',
    userHead: './images/6.jpeg',
    username: 'User 15',
    likeCount: 850,
    isLike: false,
  },
  {
    preview: './images/10.webp',
    title: '山林的rty静',
    tag: 'Tag 3md',
    userHead: './images/6.jpeg',
    username: 'User 16',
    likeCount: 950,
    isLike: true,
  },
  {
    preview: './images/11.webp',
    title: '草原的jrwtfqafa广',
    tag: 'Tag 456jmd',
    userHead: './images/6.jpeg',
    username: 'User 17',
    likeCount: 1050,
    isLike: false,
  },
  {
    preview: './images/12.jpeg',
    title: '沙漠的热znb',
    tag: 'Tag121378',
    userHead: './images/6.jpeg',
    username: 'User 18',
    likeCount: 1150,
    isLike: true,
  },
];
