export default [
  {
    preview: './videos/1.mp4',
    isMv: true,
    title: '每天花一小时化出来的帅脸',
    tag: 'Tag 1',
    userHead: './images/2.webp',
    username: 'User 1',
    likeCount: 100,
    isLike: true,
  },
  {
    preview: './videos/2.mp4',
    isMv: true,
    title: 'Basic clothes stuff',
    tag: 'Tag 2',
    userHead: './images/5.webp',
    username: 'User 2',
    likeCount: 200,
    isLike: false,
  },
  {
    preview: './videos/3.mp4',
    isMv: true,
    title: '官个宣❤',
    tag: 'Tag 5',
    userHead: './images/6.jpeg',
    username: 'User 5',
    likeCount: 500,
    isLike: true,
  },
  {
    preview: './videos/4.mp4',
    isMv: true,
    title: 'Image 3',
    tag: 'Tag 3',
    userHead: './images/9.jpeg',
    username: 'User 3',
    likeCount: 300,
    isLike: true,
  },
  {
    preview: './videos/5.mp4',
    isMv: true,
    title: 'I相信自己会越来越好的',
    tag: 'Tag 4',
    userHead: './images/4.jpeg',
    username: 'User 4',
    likeCount: 400,
    isLike: false,
  },
  {
    preview: './videos/6.mp4',
    isMv: true,
    title: '我的猫喜欢我的宝宝',
    tag: 'Tag 5',
    userHead: './images/6.jpeg',
    username: 'User 5',
    likeCount: 500,
    isLike: true,
  },
  {
    preview: './videos/7.mp4',
    isMv: true,
    title: '表面上参加：',
    tag: 'Tag 2',
    userHead: './images/5.webp',
    username: 'User 2',
    likeCount: 200,
    isLike: false,
  },
  {
    preview: './videos/8.mp4',
    isMv: true,
    title: '爱打扮外号叫什么',
    tag: 'Tag 5',
    userHead: './images/6.jpeg',
    username: 'User 5',
    likeCount: 500,
    isLike: true,
  },
  {
    preview: './videos/9.mp4',
    isMv: true,
    title: '爱自己会发光',
    tag: 'Tag 2',
    userHead: './images/5.webp',
    username: 'User 2',
    likeCount: 200,
    isLike: false,
  },
  {
    preview: './videos/10.mp4',
    isMv: true,
    title: '已更新',
    tag: 'Tag 5',
    userHead: './images/6.jpeg',
    username: 'User 5',
    likeCount: 500,
    isLike: true,
  },
  {
    preview: './videos/11.mp4',
    isMv: true,
    title: '用牛逼的口音说多邻国的第一单元',
    tag: 'Tag 2',
    userHead: './images/5.webp',
    username: 'User 2',
    likeCount: 200,
    isLike: false,
  },
  {
    preview: './videos/12.mp4',
    isMv: true,
    title: '夏日的风',
    tag: 'Tag 3',
    userHead: './images/6.jpeg',
    username: 'User 6',
    likeCount: 350,
    isLike: true,
  },
  {
    preview: './images/1.jpeg',
    title: '冬日的雪',
    tag: 'Tag 4',
    userHead: './images/6.jpeg',
    username: 'User 7',
    likeCount: 450,
    isLike: false,
  },
  {
    preview: './images/2.webp',
    title: '春日的花',
    tag: 'Tag 1',
    userHead: './images/6.jpeg',
    username: 'User 8',
    likeCount: 150,
    isLike: true,
  },
  {
    preview: './images/3.jpeg',
    title: '秋日的叶',
    tag: 'Tag 5',
    userHead: './images/6.jpeg',
    username: 'User 9',
    likeCount: 250,
    isLike: false,
  },
  {
    preview: './images/4.jpeg',
    title: '夜空的星',
    tag: 'Tag 2',
    userHead: './images/6.jpeg',
    username: 'User 10',
    likeCount: 350,
    isLike: true,
  },
  {
    preview: './images/5.webp',
    title: '晨曦的光',
    tag: 'Tag 3',
    userHead: './images/6.jpeg',
    username: 'User 11',
    likeCount: 450,
    isLike: false,
  },
  {
    preview: './images/6.jpeg',
    title: '黄昏的影',
    tag: 'Tag 4',
    userHead: './images/6.jpeg',
    username: 'User 12',
    likeCount: 550,
    isLike: true,
  },
  {
    preview: './images/7.jpeg',
    title: '月光的柔',
    tag: 'Tag 1',
    userHead: './images/6.jpeg',
    username: 'User 13',
    likeCount: 650,
    isLike: false,
  },
  {
    preview: './images/8.jpeg',
    title: '阳光的暖',
    tag: 'Tag 5',
    userHead: './images/6.jpeg',
    username: 'User 14',
    likeCount: 750,
    isLike: true,
  },
  {
    preview: './images/9.jpeg',
    title: '海风的咸',
    tag: 'Tag 2',
    userHead: './images/6.jpeg',
    username: 'User 15',
    likeCount: 850,
    isLike: false,
  },
  {
    preview: './images/10.webp',
    title: '山林的静',
    tag: 'Tag 3',
    userHead: './images/6.jpeg',
    username: 'User 16',
    likeCount: 950,
    isLike: true,
  },
  {
    preview: './images/11.webp',
    title: '草原的广',
    tag: 'Tag 4',
    userHead: './images/6.jpeg',
    username: 'User 17',
    likeCount: 1050,
    isLike: false,
  },
  {
    preview: './images/12.jpeg',
    title: '沙漠的热',
    tag: 'Tag 1',
    userHead: './images/6.jpeg',
    username: 'User 18',
    likeCount: 1150,
    isLike: true,
  },
];
